### ISSUE TITLE
Remove .NET requirement

### ISSUE THREAD

**Issue by wolfcomp** [HunterPie/HunterPie#106]
When you build, you could choose to target with `-r` this being the runtime identifier for windows it would be `win-x64` for x64 systems, and you can also append `/p:PublishSingleFile=true` to make it package all the files including .NET Runtime into the exe for windows. This is done using the `dotnet publish` command.

**Comment by wolfcomp** [comment]
It's a trade-off for not having people to download another thing.

**Comment by Haato3o** [comment]
Might consider this when I configure the CI/CD for HunterPie so it uploads the files directly to the server then

**Comment by Haato3o** [comment]
Actually, I just tested it again and noticed I compiled it as `Framework-dependent` by accident. Publishing it as `self-contained` generates a 147 MB file and a couple of native dll's. So this is a big no no from me.

**Comment by wolfcomp** [comment]
It does this to remove the requirement to install the core runtime on others computers. It will save a lot of people an extra download step, with the tradeoff being bigger file size. Microsoft states also that you could do [IL trimming](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained) to reduce file size when building `self-contained` .NET 5 it's an experimental feature, while in .NET 6 it's fully supported.

One of the caveats with running just the `framework-dependent` one is that 
1. They have to install the runtime specific version
2. The runtime might change

If you also changed to an updater that has patching done instead of downloading the entire thing again, one which is widely used [Squirrel](https://github.com/clowd/Clowd.Squirrel) as it builds delta updates that can be patched in and not be as large as the full size.

**Comment by Haato3o** [comment]
> It will save a lot of people an extra download step

Trust me, the amount of people that actually needs to download .NET is negligible compared to the active user base of HunterPie right now, and the amount of people that actually have issues downloading it and need assistance is also below 1% of the total users, so downloading it really isn't a real issue.
Making it compile as `self-contained` would bring me more issues than benefits, be a lot more time consuming since I'd have to change the self-update code, also update my API, probably deal with my file Buckets since 147 MB for file is a LOT compared to the 1.5 MB per file I have today.
As of today, I have 64 releases in the `Alpha` bucket for Patreons and 42 for the actual public releases, both buckets summed takes 160 MB. If I started publishing it as `self-contained` and have the same amount of binaries (which will definitely be, since HunterPie is in active development), that would take ~15 GB of files, which is a lot.

> Microsoft states also that you could do [IL trimming](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained) to reduce file size when building self-contained .NET 5 it's an experimental feature, while in .NET 6 it's fully supported.

IL trimming doesn't work in this case as HunterPie also has depends on Windows Forms, so that's not supported.

**Comment by Haato3o** [comment]
@Kobi-Blade The issue here is not how easy it is to migrate to a newer version, I know how to do that and I've done it multiple times. The issue is that like you said, people don't have .NET installed in their computer by default and I will be the one receiving thousands of complaints asking why their HunterPie suddenly stopped working (happened the last time I bumped from .NET 5.0 to 6.0). It is not wise to do upgrades like that when you have thousands of users.

With that said, upgrade to .NET 8.0 will only happen when 6.0 support ends (November 2024).
