### ISSUE TITLE
MHW: Monster's Parts' statuses don't update (severed/broken etc.)

### ISSUE THREAD

**Issue by Forien** [HunterPie/HunterPie#350]
Joined SOS for someone's Brachydios investigation. We cut off the tail, overlay still showed Tail as full HP red (severable) bar. 

Legacy HunterPie fails to track parts HP, but at least it recognised if parts have been destroyed.

**Comment by Haato3o** [comment]
It's impossible to track parts health when you're not party leader, other clients won't send that data to you and it's been a game limitation since its release.

Legacy HunterPie doesn't fail to track parts and also doesn't recognize that a part has been broken, it just simply sets every part health to 0 regardless if they're broken or not when you're not the party host.

HunterPie v2 will always show them as full health because that's what you have in your game's memory.

**Comment by Forien** [comment]
I've been using Legacy HunterPie and I am sure that even when I joined someone I did see which parts have been broken (they disappeared from list) with these settings:

![image](https://user-images.githubusercontent.com/11304207/213548558-176eaab1-ba9d-49fe-b27c-ca28e514534c.png)

I specifically want to be able to easily see which parts have been fully broken and which haven't. Are you sure it's not possible if I'm not a host?

**Comment by Haato3o** [comment]
The only information clients send each other about parts are tenderize timers and flinch counts, I mapped monster's flinch thresholds in v1 to be able to tell the user how many flinches until that parts break/severs, that's not really 100% accurate and pretty complex to implement as some monsters can regenerate their parts. 
That's the information v1 uses to "detect" part breaks, but it's an assumption and not really an 100% accurate detection.

**Comment by Forien** [comment]
I see, thank you for the explanation
