### ISSUE TITLE
Damage meter improvements

### ISSUE THREAD

**Issue by FerLuisxd** [HunterPie/HunterPie#396]
Is there a a reason why these are not considered?

![image](https://user-images.githubusercontent.com/29811965/221690562-1485f995-e2f4-4945-8c1d-cfdc99f6c36a.png)
Especially:
`Damage done by ailments (e.g: poison, blast)`
It could be nice to have an option to enable/disable it
Or is it a limitation?

**Comment by Haato3o** [comment]
Palamutes/palicos and companions damage are tracked now, I just forgot to update the documentation.

As for the damage done by ailments, it's not a limitation but the game doesn't keep track of who contributed the most (or who started) the ailments, so it's hard to associate that ailment damage to someone in the party. And I don't want to add an extra component in the damage meter just for it because that's not a party member
