### ISSUE TITLE
Checking new localization files got stuck

### ISSUE THREAD

**Issue by RyanLoil** [HunterPie/HunterPie#397]
Already checked:

- Folder is NOT at readonly mode
- Using UAC for Hunterpie.exe
- Update to the latest version

Environment:

- OS: Windows 11 Home 22H2 22621.1265
- Hunterpie Version: 2.7.0.80
- CPU: AMD Razen 7 5800H
- GPU: Nvidia GeForce RTX 3060 Laptop
- RAM: 40GB

Hunterpie Logs:
```
[10:27:21][Info] Initialized HunterPie Client configuration.
[10:27:22][Info] Initialized HunterPie logger
[10:27:22][Info] Loaded theme Default
[10:27:22][Info] Loaded localization en-us
[10:27:22][Info] Time taken for 'Initialize': 322ms
[10:29:22][Error] System.NullReferenceException: Object reference not set to an instance of an object.
   at HunterPie.Core.Networking.Http.HttpClientResponse.AsTextAsync()
   at HunterPie.Integrations.Poogie.Common.Models.PoogieResult`1.From(HttpClientResponse response)
   at HunterPie.Integrations.Poogie.Common.PoogieConnector.Get[T](String path)
   at HunterPie.Integrations.Poogie.Localization.PoogieLocalizationConnector.GetChecksums()
   at HunterPie.Update.Remote.UpdateApi.GetLocalizationsChecksum()
   at HunterPie.Update.UpdateService.UpdateLocalizationFiles()
   at HunterPie.Update.UpdateUseCase.Exec(UpdateViewModel vm)
   at HunterPie.App.SelfUpdate()
   at HunterPie.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Screenshot:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/50242494/221739414-6634c97d-510c-4d35-a039-80f9371bbea3.png">

**Comment by Haato3o** [comment]
Looks like you're on an old version of HunterPie (<= 2.7.0.100) and something is blocking your HunterPie from reaching the server's to get the localization checksums. Verify the following:

- Make sure nothing is messing up the connection (antivirus, firewall, VPNs, Hamachi or anything else that  can affect the internet connection)
- Make sure your internet can resolve the server's DNS (you can see that by running ping `api.hunterpie.com` in your cmd). If the connection times out then there's something wrong with your PC/Internet, in that case, it's either DNS issues or something wrong in your router,
- Try either flushing your DNS or setting another DNS resolver (like Google's `8.8.8.8` or Cloudflare's `1.1.1.1`)
- Make sure your PC is using TLS 1.2 or above.

If nothing works out, try connecting to another internet if possible and see if that works.

**Comment by RyanLoil** [comment]
Understand thx

**Comment by RyanLoil** [comment]
<img width="732" alt="image" src="https://user-images.githubusercontent.com/50242494/221745408-295bc962-320d-4d01-a98f-40cd2fa9a804.png">
My country have National Firewall and I think api.hunterpie.com is being block, so I use VPN with browser directly reach api.hunterpie.com and got this:
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/50242494/221746088-bd72ebac-5dce-40d5-b0be-4027f1665120.png">
My VPN works fine confirmed by connecting google and it's DNS normally.
<img width="492" alt="image" src="https://user-images.githubusercontent.com/50242494/221746148-d6dffada-4d88-4b6a-9bc2-003d41cb304b.png">

**Comment by RyanLoil** [comment]
Solved. Hunterpie didn't use system proxy. It's not a bug, but a feature, please consider this feature in the future, thank you.

**Comment by Zoss0** [comment]
Having this issue as well - virtually the same environment as OP, except Win 10.
Other steps taken - tethering over USB Ethernet from Mobile to Desktop - same issue.
DNS set to 8.8.8.8 - same result.
DNS set to homelab server - same result.
Using uncompressed new pull from Github, version: 2.7.0.80

NSLookup returns:
Non-authoritative answer:
Name:    api.hunterpie.com
Addresses:  2606:4700:3033::6815:2e36
          2606:4700:3032::ac43:dfe2
          104.21.46.54
          172.67.223.226
Pings:
Pinging api.hunterpie.com [2606:4700:3032::ac43:dfe2] with 32 bytes of data:
Reply from 2606:4700:3032::ac43:dfe2: time=3ms
Reply from 2606:4700:3032::ac43:dfe2: time=3ms
Reply from 2606:4700:3032::ac43:dfe2: time=3ms
Reply from 2606:4700:3032::ac43:dfe2: time=3ms

Ping statistics for 2606:4700:3032::ac43:dfe2:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 3ms, Maximum = 3ms, Average = 3ms

Pinging api.hunterpie.com [172.67.223.226] with 32 bytes of data:
Reply from 172.67.223.226: bytes=32 time=2ms TTL=57
Reply from 172.67.223.226: bytes=32 time=3ms TTL=57
Reply from 172.67.223.226: bytes=32 time=3ms TTL=57
Reply from 172.67.223.226: bytes=32 time=3ms TTL=57

Ping statistics for 172.67.223.226:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 2ms, Maximum = 3ms, Average = 2ms

IPConfig was flushed numerous times.
No outbound firewall interfering.

**Comment by Haato3o** [comment]
@Zoss0 Try enabling debug messages, it will show you the reason for the error.

Go to client settings -> Enable feature flags -> Go to feature flags tab -> Enable advanced dev tools (leave and go back into settings so it reloads the UI) -> Go to Dev tools -> Scroll all the way down and change log level to Debug then restart HunterPie

**Comment by Zoss0** [comment]
@Haato3o 
Sorry, because it's a "new" install - I can't get pass the "checking for new localisation files" screen - therefore I can't get to the main window. Is there a place in the .json config (or any other config file) I can set that parameter or am I missing something?

**Comment by Haato3o** [comment]
@Zoss0 
![image](https://user-images.githubusercontent.com/35552782/224581652-cd2563ea-6534-43d6-beae-3327fd56718b.png)

Change the value to `0` instead of `1`, restart HunterPie. It will also generate a `HunterPie_Log.txt` file. Just paste the log here.

**Comment by Zoss0** [comment]
Unfortunately it isn't giving us any more information.

`[10:28:49 AM][Info] Initialized HunterPie Client configuration.
[10:28:49 AM][Info] Initialized HunterPie logger
[10:28:49 AM][Info] Loaded theme Default
[10:28:49 AM][Info] Loaded localization en-us
[10:28:49 AM][Info] Time taken for 'Initialize': 245ms
[10:28:53 AM][Error] System.NullReferenceException: Object reference not set to an instance of an object.
   at HunterPie.Core.Networking.Http.HttpClientResponse.AsTextAsync()
   at HunterPie.Integrations.Poogie.Common.Models.PoogieResult`1.From(HttpClientResponse response)
   at HunterPie.Integrations.Poogie.Common.PoogieConnector.Get[T](String path)
   at HunterPie.Integrations.Poogie.Localization.PoogieLocalizationConnector.GetChecksums()
   at HunterPie.Update.Remote.UpdateApi.GetLocalizationsChecksum()
   at HunterPie.Update.UpdateService.UpdateLocalizationFiles()
   at HunterPie.Update.UpdateUseCase.Exec(UpdateViewModel vm)
   at HunterPie.App.SelfUpdate()
   at HunterPie.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

![image](https://user-images.githubusercontent.com/5527179/224582576-0f7a286f-ed95-4dd3-a74e-2ad9e28328c9.png)

**Comment by Haato3o** [comment]
Open `cmd` and run this command: `REG QUERY HKEY_CURRENT_USER\SOFTWARE\HunterPie /v client_id`

Send me the value you got, that's the client id of your HunterPie so I can check if my Cloudflare WAF isn't blocking the requests, and if my API is receiving them in the first place

**Comment by Zoss0** [comment]
HKEY_CURRENT_USER\SOFTWARE\HunterPie
    client_id    REG_SZ    A44297044974EA27AF35B4582D3B02CF

**Comment by Haato3o** [comment]
Apparently your client was able to reach the API, and it did answer with `200` and the right response. Do you happen to have a VPN?

**Comment by Zoss0** [comment]
I have one, but I don't use it most of the time. Endpoint is 168.138.10.32 which is an Oracle owned network...which their network does come show up in various blacklist sometimes.

![image](https://user-images.githubusercontent.com/5527179/224583992-5de6e705-2e26-4bdc-becf-bd7bc55967aa.png)


Throughout this process it has not been touched though.

**Comment by Haato3o** [comment]
Well, looking at my WAF's logs, there are requests with that client id coming from two different IPs, one in the USA and one in Australia, which is typically something related to VPNs, my bet is that there's something messing up with the connection that allows HunterPie to request the server but is messing with the response somehow

**Comment by Zoss0** [comment]
Both my IP and the VPNs are Australian, if that helps...
Maybe in the past I've used an American IP - but none come to mind recently. What's the timestamp on the American one?

**Comment by Haato3o** [comment]
![image](https://user-images.githubusercontent.com/35552782/224584559-58633b2e-f605-43b1-9909-5de8daf24fea.png)

The timestamps are in GMT-3 since that's my timezone. The requests were received ~50 minutes ago

**Comment by Zoss0** [comment]
So that leaves two possibilities.

One, I'm forgetting about something that is causing my computer to have an American IP...which would be odd, but not improbable. I have a couple of devices here but my network is pretty quiet and there's no router level VPN.
I also barely was awake 50 minutes ago, only rolled out for this.

Checking my DHCP leases in my router, all devices are accounted for, and not like they should be calling out to your WAF anyway as some are incapable or don't have HunterPie.

Two, those keys have had collision? Maybe?

Can we regenerate the key?

**Comment by Haato3o** [comment]
1. Well, the requests I got were from when you started HunterPie to check for the log file (your post on Github with the log file was exactly 3 minutes after the timestamp in the API's logs), the reason why there are multiple requests to the same endpoint is because internally HunterPie has a retry system, so when one request fails, it will retry up to 5 times.

2. Extremely unlikely, the `client_id` is generated only once using an algorithm to generate safe random numbers, the `session_id` (the one in the screenshot) is an UUID generated everytime you start HunterPie, the chances of a collision for both of those values at the same time is pretty much impossible, there's also the fact that both of those requests with different IDs have the exact same User-Agent

3. Also very unlikely, HunterPie has around ~20k users monthly, the amount of people having this issue is below 0.05%, if it was a code error, the percentage would be a lot higher.

**Comment by Zoss0** [comment]
Any suggestions/ideas?

If I regen the key, and restart HunterPie and you see two different IPs again, could that help in troubleshooting code?

**Comment by Haato3o** [comment]
I don't think so because it's not code related, HunterPie just uses the C# `HttpClient` for requests, all it does is pass the URL it should request and then parse the response it got, I don't know the underlying implementation of that HttpClient, as that is in Microsoft's standard library for HTTP

**Comment by Haato3o** [comment]
You can probably try downloading the latest files by hand, but that doesn't guarantee that you won't have issues with requests in the most recent version.

Here's the link if you want to try it out: https://api.hunterpie.com/v1/version/latest

**Comment by Zoss0** [comment]
Well, the latest files worked for some reason.

Doing a fresh test with files from releases from Github, I extracted into a separate folder (but the same root folder) as the working latest files and I still get the same effect.

So whatever you've changed in your dev branch is working...?

**Comment by Haato3o** [comment]
It's not dev branch, the latest binary is the one in the main branch, I just don't upload them to Github releases everytime because it's way too much work for something that has a built-in self update.

As for what I've changed in the latest release:
The thing that caused the localization update to be stuck was a `NullPointerException`, the same one you got in the log file, the thing is, that is not the issue itself, just one of it's consequences. Your network issue still exists, so there's a chance your HunterPie won't ever get updates because of that issue, the only difference is that after `v2.7.0.103`, HunterPie ignores failed requests

**Comment by Zoss0** [comment]
I see. I suppose I could just manually download if you're going to keep the (I assume) new try catch in your next release. 

Well, I guess I'm an edge case so you could just not bother with it, or I can try to help out by compiling and stepping through your code - but I don't know how to compile your project (No section on it, not that you have to) (I haven't worked with others yet)

Anything I can do on my end to help out?

**Comment by Haato3o** [comment]
Well, if you could put a breakpoint in the HttpClient, it would be great. I don't think the request is throwing an exception, it's just not being able to receive the response of the API.
And to build the application you just need to clone it recursively and build it by pressing F5, just that. Also, you might need to create a Languages folder in your output folder (The release/net6-runtime), otherwise the build might fail

**Comment by Zoss0** [comment]
Sorry this took so long. Apparently IT is also the concrete retainer wall builder as well.

```
System.Net.Http.HttpRequestException
  HResult=0x80131620
  Message=An error occurred while sending the request.
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.HttpConnection.<SendAsyncCore>d__64.MoveNext()
   at System.Net.Http.HttpConnectionPool.<SendWithVersionDetectionAndRetryAsync>d__84.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d.MoveNext()
   at HunterPie.Core.Networking.Http.HttpClient.<RequestAsync>d__31.MoveNext() in D:\Data\Development\HunterPie\HunterPie.Core\Networking\Http\HttpClient.cs:line 83

Inner Exception 1:
IOException: The read operation failed, see inner exception.

Inner Exception 2:
AuthenticationException: Authentication failed, see inner exception.

Inner Exception 3:
Win32Exception: The message received was unexpected or badly formatted.
```

I think what you're doing is sending _request.Headers to somewhere and the formatting is buggered?
_request.Headers's values seem to be...

```
+		_request.Headers	{X-Client-Id: A44297044974EA27AF35B4582D3B02CF
X-Supporter-Token: 
X-App-Version: 2.7.0.109
X-HunterPie-Client: v2
X-Session-Id: 1adfe538-021e-46fe-b3db-a1e2e27bff9e
User-Agent: HunterPie/2.7.0.109 (Microsoft Windows NT 10.0.19045.0)
}	System.Net.Http.Headers.HttpRequestHeaders
```

**Comment by Haato3o** [comment]
It has nothing to do with the headers, they're fine.

What I think could be happening is that something is closing the connection early and making it so HunterPie can't read the body of the response, which would explain the `Inner Exception 1: IOException: The read operation failed, see inner exception.`

Then looking at the `Inner Exception 2: AuthenticationException: Authentication failed, see inner exception.`, that usually means something is not configured right in your machine, it is probably using an older version of TLS or SSL.

Going deeper to `Inner Exception 3: Win32Exception: The message received was unexpected or badly formatted.`, that error happens when you have a TLS handshake error.

You can try setting the default [TLS to 1.2](https://learn.microsoft.com/en-us/mem/configmgr/core/plan-design/security/enable-tls-1-2-client).


On a side note, the different incoming IPs issue is still happening, one is from an AWS server in the USA and the other is from Australia.

![image](https://user-images.githubusercontent.com/35552782/227698235-d3da470b-b2bf-4016-940f-36a04c381ee6.png)

**Comment by Zoss0** [comment]
I've found the fix. All this talk about TLS and SSL, all that. I run a privacy script to harden my install.

privacy.sexy

I had to **REVERT** the TLS changes it does to fix this. I don't know which one, but I'll experiment later to find out. But enable these breaks it. Reverting it to decrease security, fixes it.

![image](https://user-images.githubusercontent.com/5527179/227710827-f8d5a26e-af4f-4d16-b05e-8236771df87e.png)
If someone else uses this style of script to harden up - reverting the changes should fix it. Just type TLS and revert the results.

![image](https://user-images.githubusercontent.com/5527179/227710882-3bc7d7ab-3b3e-481c-936f-4feed2e8c96e.png)

**Comment by Haato3o** [comment]
Oh, glad you found the issue. I'm not sure why enabling TLS 1.3 would break the connection though, in theory Cloudflare should support it and my API should also support it too. Though 50% of the requests I get are using TLS 1.2 and the other half is TLS 1.1, Cloudflare doesn't show any request with 1.3 for me
