### ISSUE TITLE
Question: FPS of the MHR is capped at 60.

### ISSUE THREAD

**Issue by yagi2** [HunterPie/HunterPie#403]
Hello. Thank you for the great software.

Running HunterPie will run the game with a FPS limit of 60, regardless of the in-game settings.
Is this an intended specification? It would be great to be able to run the game and HunterPie at the same time with unlimited FPS or 60+ if possible.

**Comment by Haato3o** [comment]
HunterPie uses WPF for rendering, and WPF is capped at 60 FPS, there's not much I can do about it. However, if for some reason it is locking your whole screen refresh rate at 60Hz, it's probably because of GSync.
In that case you have two options, either disable GSync for windowed applications, or disable it individually for HunterPie by using NVidia Profile Inspector

![image](https://user-images.githubusercontent.com/35552782/226766029-d89784de-4fc2-4c1c-94c4-888e3feee20d.png)

**Comment by yagi2** [comment]
Thank you for your kind attention. 
I will review the GSync settings as my problem was an issue with the FPS of the game being fixed at 60.
