### ISSUE TITLE
Deleting Account/Save Backups

### ISSUE THREAD

**Issue by PhynixAbyss** [HunterPie/HunterPie#446]
Will there be or is there a delete Account Button?

When exactly does it Auto Save? If i close the Game? Every 72h, even when the Game is closed?

I imagine you play, close it saves and this save could be corrupted in the next update, but you also dont play and it saves the corrupted file, because you did go over the 72h mark.

That's why i am wondering when it exactly saves files.

**Comment by Haato3o** [comment]
> Will there be or is there a delete Account Button?

Yes, I just haven't had the time to add it yet

> When exactly does it Auto Save? If i close the Game? Every 72h, even when the Game is closed?

Everytime you start the game, it will check if it can upload a new backup based on your last upload date, if it has been 72 hours since your last upload, then it will pack all your save files into a zip and upload to the cloud. This only happens once you start the game with HunterPie running on the background.
