### ISSUE TITLE
Overlay not showing on discord stream

### ISSUE THREAD

**Issue by AtomikHeh** [HunterPie/HunterPie#535]
So I'm having an issue where when I steam my game with HunterPie on discord it won't show the overlays, however it works perfectly fine on my friend's game. I can always stream my whole screen and it'll show the overlay so it's not that bad of an issue but not being able to quickly stream my game with the overlay with a keybind is kind of a pain in the ass. Any idea why that might be ?

**Comment by Haato3o** [comment]
Well, that's not something that HunterPie can control, it's related to how Discord captures games. Some people have reported that playing in fullscreen (with DX12) made it capture the overlay with the game, so maybe you could try that.

I can't guarantee that will work though, because again, it's out of my control how Discord decides to capture the game
